version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: usuario
      POSTGRES_PASSWORD: senha
      POSTGRES_DB: gestor_tarefas
    ports:
      - "5433:5432"

  web:
    build: .
    command: flask run --host=0.0.0.0
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      FLASK_APP: run
      FLASK_ENV: development
      DATABASE_URL: postgres://usuario:senha@db:5432/gestor_tarefas
